export default {
  title: 'light',
  background: {
    body: '#ebf2f5',
    form: '#fff',
    border: '#D3E2E5',
    border_map: '#B3DAE2',
    active: '#EDFFF6',
    border_active: '#A1E9C5',
    text_active: '#37C77F',
    input: '#F5F8FA',
    primary: '#29B6D1',
    secondary: '#ffd666',
    linear_primary: '#29B6D1',
    linear_secondary: '#00C7C7',
    button: '#15c3d6',
    button_hover: '#17d6eb',
    button_hover_light: '#96feff',
    confirm: '#3CDC8C',
    confirm_text: '#fff',
    confirm_hover: '#36CF82',
    btn_access: '#12D4E0',
    btn_access_hover: '#96FEFF',
    btn_login: '#ebf2f5',
  },
  font: {
    primary: '#0089a5',
    title: '#5C8599',
    base: '#8FA7B3',
    text_access: '#fff',
    text_access_hover: '#15C3D6',
    text_login: '#15c3d6',
  },
};
